---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # naming the deployment

spec:
  selector:
    matchLabels:
      app: nginx # look for this label to match this k8 service


  replicas: 2

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: abumarwa/nginx:latest
        ports:
        - containerPort: 80

# create a kubernetes nginx-service.yml